name: BMO on Linux

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.9', '3.10' ]

    name: BMO with Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Build and test"
        run: |
          make ci

      - name: "Upload to pypi.org (nightly)"
        env:
          PYPI_UPLOAD_TOKEN: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: |
          poetry version $(poetry version -s)-nightly-$(date '+%s')
          make upload

      - name: "Upload to pypi.org"
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          PYPI_UPLOAD_TOKEN: ${{ secrets.PYPI_UPLOAD_TOKEN }}
        run: |
          make upload
